'use client';

import React, { useState } from 'react';
import { Download } from 'lucide-react';
import { GeneratedReportRow } from '@/data/reports';

interface GeneratedReportsTableProps {
  data: GeneratedReportRow[];
}

export const GeneratedReportsTable: React.FC<GeneratedReportsTableProps> = ({ data }) => {
  // Tracking which specific report row is currently downloading
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownloadReport = (id: string, reportName: string) => {
    setDownloadingId(id);

    // Simulate server-side document compilation delay (1.2 seconds)
    setTimeout(() => {
      try {
        // Create an illustrative formatted text report matching your schema
        const reportContent = `===========================================================
TRIOS PLATFORM GENERATED EXPORT LOG
===========================================================
Report ID:       ${id}
Report Type:     ${reportName}
Generated By:    System Administrator
Timestamp:       ${new Date().toLocaleString()}
Status:          Verified & Authorized

-----------------------------------------------------------
This is an authentic system generated analytical digest. 
All data values match transaction logs and KYC metrics 
active in the Trios database.
===========================================================
`;

        // Convert the string into a text blob representing the PDF/TXT document
        const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        
        // Create an invisible download anchor to trigger the browser saving mechanism
        const link = document.createElement('a');
        link.href = url;
        
        // Clean name format for the saved file (e.g. monthly_vendor_revenue_report.txt)
        const safeName = reportName.toLowerCase().replace(/[^a-z0-9]/g, '_');
        link.setAttribute('download', `${safeName}_${id.replace('#', '')}.txt`);
        
        document.body.appendChild(link);
        link.click();
        
        // Clean up memory
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      } catch (err) {
        console.error('Failed to generate report download:', err);
      } finally {
        setDownloadingId(null);
      }
    }, 1200);
  };

  return (
    <div className="w-full bg-white rounded-3xl border border-neutral-100 shadow-[0_2px_10px_-4px_rgba(0,0,0,0.05)] overflow-hidden flex flex-col max-w-[1100px] select-none animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="px-8 py-5 border-b border-neutral-100 bg-[#F8F9FA]">
        <h3 className="text-sm font-bold text-neutral-900 leading-none">Generated Platform Reports</h3>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse min-w-[750px]">
          <thead>
            <tr className="bg-white border-b border-neutral-100">
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Report ID</th>
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Report Name</th>
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Generated By</th>
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Date Created</th>
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Status</th>
              <th className="px-8 py-5 text-sm font-bold text-neutral-900">Action</th>
            </tr>
          </thead>
          <tbody>
            {data.map((row, index) => {
              const isProcessing = row.status === 'Processing';
              const isDownloading = downloadingId === row.id;
              return (
                <tr
                  key={index}
                  className="border-b border-neutral-100 last:border-none hover:bg-neutral-50/50 transition-colors"
                >
                  <td className="px-8 py-5 text-[15px] text-neutral-600 font-medium">{row.id}</td>
                  <td className="px-8 py-5 text-[15px] text-neutral-600 font-medium">{row.name}</td>
                  <td className="px-8 py-5 text-[15px] text-neutral-600 font-medium">{row.generatedBy}</td>
                  <td className="px-8 py-5 text-[15px] text-neutral-600 font-medium">{row.dateCreated}</td>
                  
                  {/* Status Badge */}
                  <td className="px-8 py-5">
                    <span className={`inline-flex px-3 py-1.5 rounded-lg text-xs font-bold leading-none ${
                      row.status === 'Completed' 
                        ? 'bg-[#E5F5E8] text-[#168E33]' 
                        : 'bg-[#E4E4E7] text-[#52525B]'
                    }`}>
                      {row.status}
                    </span>
                  </td>

                  {/* Dynamic Download Action */}
                  <td className="px-8 py-5">
                    {row.status === 'Completed' ? (
                      <button
                        onClick={() => handleDownloadReport(row.id, row.name)}
                        disabled={isDownloading}
                        className="h-9 px-4 bg-[#6312E1] hover:bg-[#520cbd] disabled:opacity-50 text-white text-xs font-bold rounded-lg flex items-center justify-center gap-1.5 transition-colors focus:outline-none select-none shadow-sm shadow-[#6312E1]/10 min-w-[80px]"
                      >
                        {isDownloading ? (
                          <svg className="animate-spin h-3.5 w-3.5 text-white" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                          </svg>
                        ) : (
                          <>
                            <Download className="w-3.5 h-3.5" /> PDF
                          </>
                        )}
                      </button>
                    ) : (
                      <span className="text-xs font-semibold text-neutral-400">Processing...</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};